deps.minecraft=1.21.1
deps.fabric-api=0.116.9+1.21.1
deps.moonlight=1.21-2.29.22-fabric
deps.forge_config_api_port=21.1.6
deps.modmenu=11.0.4
deps.minecraft_version_range=>=1.21 <1.21.2
deps.parchment=1.21.1:2024.11.17
deps.emi=1.1.24+1.21.1
deps.jei=19.27.0.340
publish.additionalVersions=1.21
deps.mcqoy=17CKhwqV
deps.yacl=3.8.2+1.21.1

deps.mousetweaks=1.21-2.26-fabric
deps.fractal=1.4.0+1.21.1
deps.controlify=3.0.0+lts+1.21.1-fabric