deps.minecraft=26.1.2
deps.neoforge=26.1.2.43-beta
deps.rrv=8.2.0+26.1.2
deps.jei=29.5.0.28
deps.loader_version_range=[4,)
deps.neo_version_range=[26,)
deps.minecraft_version_range=[26, 26.2]
deps.mcqoy=yHGo6VsD
deps.yacl=3.9.3+26.1
publish.curseforge_minecraft_version=26.1.2

deps.mousetweaks=26.1-2.31-neoforge
deps.fractal=2.1.0+26.1-neoforge
deps.controlify=3.0.1+26.1-neoforge