deps.minecraft=26.1.2
deps.fabric-api=0.149.0+26.1.2
deps.modmenu=18.0.0-alpha.8
deps.rrv=8.2.0+26.1.2
deps.jei=29.5.0.28
deps.minecraft_version_range=~26.1
deps.mcqoy=17CKhwqV
deps.yacl=3.9.3+26.1-fabric
publish.curseforge_minecraft_version=26.1.2

deps.mousetweaks=26.1-2.31-fabric
deps.fractal=1.6.1+26.1
deps.controlify=3.0.1+26.1-fabric