deps.minecraft=1.20.1
deps.forge=1.20.1-47.4.10
deps.jei=15.20.0.127
deps.loader_version_range=[4,)
deps.forge_version_range=[47,)
deps.minecraft_version_range=[1.20.1]
deps.parchment=1.20.1:2023.09.03
deps.moonlight=1.20-2.16.15-forge
deps.emi=1.1.22+1.20.1
deps.fabric_api=0.92.6+1.11.14+1.20.1

deps.create=0.5.1.j
deps.mousetweaks=1.20.1-2.25.1-forge
deps.controlify=2.1.9-mc1.20.1-forge
deps.yacl=3.6.6+1.20.1-forge